ChangeLog, R/calendar.R, man/bizdays.Rd
Change to the direct use of holiday calendars of major financial centers from the package `timeDate`.
=> fixed bug in bizdays() #124

R/newarima2.R
Save the result of length(x) to serieslength so the calculation doesn't need to be repeated needlessly.
=> Remove redundant length(x) calculation

R/errors.R, inst/tests/test-accurary.R
Add more unit tests for ```accuracy()```. Accuracy from the fitted models should be worse than accuracy of a model fit on simulated data from the selected model specification.
=> Test accuracy for arima, ets, lm, and tbats objects

R/arima.R
When using a previously fitted model in `Arima` with a mismatched `xreg` (either missing or wrong size),  one gets this error message which is not very informative:
```
Error in stats::arima(x = x, order = order, seasonal = seasonal, xreg = xreg,  : 
wrong length for 'fixed'
```
I added the same checks & error messages used in `forecast.Arima`. The only exception is that I omitted `getxreg(object)`, is this extra call necessary? should it be included instead of just `object$xreg`?
Trailing whitespaces were also deleted (I have emacs set up to automatically do that... figured you wouldn't mind?).
Here's some sample code to see the errors:
```
x <- rnorm(100)
xreg <- matrix(rnorm(200), ncol = 2)
fit <- Arima(x, order = c(1, 0, 0), xreg = xreg)
##
x2 <- rnorm(100)
xreg2 <- matrix(rnorm(200), …
```
=> Give informative error when using previous model with mismatched xreg

DESCRIPTION, NAMESPACE, R/ggplot.R, man/geom_forecast.Rd
stat_forecast() should be rarely used as per Hadley's recommendation.
geom_forecast() will now generate forecasts unless specified otherwise.
Fixed geom_forecast(fc) not working with univariate time series. You now
must specify a series when using geom_forecast(fc) with multivariate
series. (Best solution I could find so far).
Removed test functions.
=> ggplot fixes and made geom_forecast() more general

R/nnetar.R, man/nnetar.Rd
I noticed a bug in `nnetar` where when NAs were present, sometimes the fitted values were not aligned correctly with the original series. 
This is caused by line 100
```
out$fitted[j] <- fits
```
since `j` is not always the same length as `fits` in which case it often gets recycled instead of giving an error.
I also added some warnings when there are NAs, and modified the fitted series to output `NA` instead of `0` for values with were ignored due to being missing.
To test try:
- Here one would expect a single NA in the first value, which is correct
```
x <- ts(rnorm(15))
nn_fit <- nnetar(x, p=1)
nn_fit$fitted
```
- Here we would expect the first value to be missing due to the lag, and the second and third values to be missing (being the original NA and the value which has it as a lag). …
=> Fix to NA induced bug in nnetar

R/nnetar.R
After thinking a bit more about #254 I think this should be sufficient to address the most common scenarios. 
- Stop with error message if series is too short
- If time series frequency doesn't match between old data and new, give a warning but continue fitting after coercing the new series to the old frequency.
Feel free to close #254 if you agree that this should work for now. 
Also, if you decide to merge both this and #253, I can rebase one of the branches to avoid any merge conflicts.
=> Add data checks to nnetar() from #254

R/tsdiag.R
The 0th lag in the acf function creates a scaling issue that makes the ACF plot impossible to view.
The Acf function from this forecast package ignores the 0th lag and makes for a much better plot.
=> tsdiag: Change acf to Acf

R/ggplot.R, man/forecastplot.Rd
Colours are now on a fixed scale as is in plot.forecast, and the lightest colour has been further shifted. These shades closer represent plot.forecast().
=> Adjusted colours for autoplot.forecast and geom_forecast()

R/arima.R, R/newarima2.R, man/arima.Rd, man/auto.arima.Rd
I've added an argument to the Arima function to allow the user to select the optimization algorithm used in the call to stats::arima. The current implementation uses the default BFGS algorithm as set by stats::arima, and when BFGS wasn't converging, I added this functionality.
P.S. Thanks for this very well written forecast package. I'm typically a Python user, but your auto.arima implementation all but forced me to switch for the work I'm doing with time series modelling.
=> Arima optim.method

R/ggplot.R, man/seasonplot.Rd
Issue #310 
Using the continuous=TRUE parameter (default FALSE)
Works with numerical colours and hex.
seasonplot(AirPassengers, col=1:2)
ggseasonplot(AirPassengers, col=1:2)
ggseasonplot(AirPassengers, col=1:2, continuous = TRUE)
ggseasonplot(AirPassengers, col=c("#000000","#FF0000"), continuous = TRUE)
=> Added support for continuous colouring in ggseasonplot()

R/ggplot.R, man/gglagplot.Rd
Maybe this should be restricted to be only when seasonal=TRUE
#320
gglagplot(ausbeer, do.lines=FALSE, labels = FALSE, lags=9, continuous = FALSE)
=> Added a continuous parameter to allow for discrete lag colours

R/lm.R
Removed fit$x and fit$data, resolves dwtest() issue #329.
```R
library(fpp)
fit1 <- tslm(sales ~ advert, data=advert)
fit2 <- lm(sales ~ advert, data=advert)
dwtest(fit1)
dwtest(fit2)
fc1 <- forecast(fit1, newdata=data.frame(advert=1:7))
fc2 <- forecast(fit2, newdata=data.frame(advert=1:7))
plot(fc1)
autoplot(fc1)
plot(fc2)
autoplot(fc2)
```
=> Made tslm() have identical object structure as lm()

R/ggplot.R
* Fixed geom_forecast(forecast) when forecast does not have confidence intervals #337
* Improved geom_forecast() handling autoplot.mts() changes (allowing facetting) for using geom_forecast(forecast, series="series1").
* Made fortify.forecast() better handle as.data.frame.forecast() and sanitisation of PI argument.
* Removed unnecessary ggplot grouping when plot.conf=FALSE (as only one line is drawn)
=> Fixes to geom_forecast()

R/lm.R
Fixes issue when functions of trend and season are used, without using trend and season as variables themselves.
For example:
```R
fit <- tslm(AirPassengers~poly(trend,3)+season)
forecast(fit, h=12)
```
Would error on not finding trend.
=> Made forecast.lm() always generate trend+season into data

R/simulate.R
We want to keep the coefficients that are different from 0 when doing this summation; code in commit 1eb839c kept coefficients with small absolute value instead of large.
=> Fix bug in myarima.sim introduced in commit 1eb839c.

R/lm.R
Fix for #387.
This code is from version 7.1, which appears to change the formula's environment, which presumably influences where `...` is extracted from.
=> tslm() `...` scoping fix

R/ggplot.R
Fix for #377
```R
beer2 <- window(ausbeer, start=1992)
gglagplot(beer2, lags=9, do.lines=FALSE, continuous=FALSE)
```
=> Improved seasonal colours for gglagplot()

R/season.R, man/forecast.stl.Rd
Presumably all fitted values should be backtransformed? Or none of them? Which is preferred?
=> stlm() now backtransforms fitted values

R/season.R
```R
b <- stlm(USAccDeaths, modelfunction = Arima)
c <- stlm(USAccDeaths, model=b)
```
Runs only when `model$modelfunction` accepts the `model` argument.
Enhancement #303
=> Added generic support for refitting custom modelfunction

R/arfima.R
fit$x <- x is redundant (and may cause issues with BoxCox transformations)
The old model's residuals, fitted, and lambda values are removed for efficiency and to improve function's robustness.
=> Made arfima re-fitting more robust

R/ggplot.R
Now always sets colour according to series, not only when series colour is inherited from ggplot() mapping. (Usually from autoplot.mts)
```R
autoplot(USAccDeaths) + 
geom_forecast(snaive(USAccDeaths), series="Seasonal Naive", plot.conf = FALSE) + 
geom_forecast(naive(USAccDeaths, h=24), series="Naive", plot.conf = FALSE) +
geom_forecast(forecast(ets(USAccDeaths)), series="ETS", plot.conf = FALSE) + 
guides(colour=guide_legend(title="Forecast"))
```
=> Enhanced geom_forecast(series=*) functionality

R/ggplot.R, R/mforecast.R, man/geom_forecast.Rd
- mforecast support
- rewritten Geom structure
- Added support for forecasts of length 1 (and 0)
- Custom geom_forecast() draw_key
- Far more structurally robust
- Clearer code
- Removed aesthetic warnings
Code sample:
```
ldeaths <- cbind(mdeaths, fdeaths)
autoplot(USAccDeaths) + geom_forecast()
autoplot(ldeaths) + geom_forecast()
fit <- tslm(ldeaths ~ trend + season)
mfcast <- forecast(fit, h=24)
ggplot() + geom_forecast(mfcast)
ggplot() + geom_forecast(mfcast, series = TRUE) # Anything without a name for each series will find the series name
ggplot() + geom_forecast(mfcast, series = c("Male deaths", "Female deaths")) # But it can be set manually if it doesn't work
autoplot(ldeaths) + geom_forecast(h=1)
```
=> geom_forecast() overhaul

R/residuals.R, R/simulate.R
The residuals in `object$residuals` for `nnetar` correspond to the difference between the fitted values and the original series. I modified the code to get the actual white noise residuals from the fitted `nnet` models (but only when necessary, meaning the user requests "innovations" _and_ `lambda` is not NULL).
I also updated `simulate.nnetar` to use the new `residuals` method, for both clarity and efficiency.
=> nnetar residuals

R/ggplot.R, man/autoplot.ts.Rd
Now when `facets=TRUE`, `colour=FALSE`, unless specified directly with `autoplot(mts, colour=TRUE, facets=TRUE)`
=> Improved default autoplot.mts interaction when setting facets=TRUE

R/clean.R
Previous behavior:
> na.interp(ts(array(c(rnorm(100), NA, rnorm(100)))))
Error in na.interp(ts(array(c(rnorm(100), NA, rnorm(100))))) : 
The time series is not univariate.
=> Accept ts based on 1-dim array

R/arima.R
Currently if an existing model has the bias adjustment parameter set, then this is dropped when passing the model to Arima. This change checks if the lambda already has a bias adjustment set (since lambda parameter defaults to coming from the original model). Not sure if this change should be implemented in arima2 instead.
=> Pick up biasadj from existing Arima model

R/theta.R, tests/testthat/test-forecast2.R, tests/testthat/test-season.R, tests/testthat/test-thetaf.R
This looks like a corner case where the theta model fails on a constant series
```
> data <- ts(c(950,950,950,950,950,950,950,950,950,950,950,950,950,950,950,950,950,950,950,950), f = 4)
> thetaf(data)
Error in if (seasonal) { : missing value where TRUE/FALSE needed
```
It appears line 89 of `theta.R`  needs to be protected from `NA`.
This PR adds that protection and tests for this (and other forecast functions like `rwf()`, `meanf()`, etc) to the test suite.
FYI, `devtools::test()` is throwing some errors/warnings unrelated to this on my machine:
```
> test()
Loading forecast
Loading required package: testthat
Attaching package: ‘testthat’
The following object is masked from ‘package:devtools’:
setup
This is forecast 8.3 
Want to meet other forecasters? Join the International Institute …
```
=> Protect thetaf from constant series

R/HoltWintersNew.R, R/acf.R, R/adjustSeasonalSeeds.R, R/arfima.R, R/armaroots.R, R/bats.R, R/clean.R, R/dshw.r, R/errors.R, R/ets.R, R/etsforecast.R, R/forecast.R, R/forecast2.R, R/forecastBATS.R, R/forecastTBATS.R, R/ggplot.R, R/lm.R, R/mstl.R, R/msts.R, R/newarima2.R, R/nnetar.R, R/residuals.R, R/season.R, R/simulate.R, R/spline.R, R/tbats.R, R/theta.R, R/unitRoot.R
Throughout forecast, `&` and `|` are used when `&&` and `||` would be more appropriate. I've changed some lines where such a change is uncontroversial, *viz.* statements within `if` and `while`. 
Though these forms typically have better performance because of their short-circuiting, not all cases will experience much of a performance increase. Nonetheless, I noticed a few within (nested) loops that probably will.
=> Use long-form && || in if/while's where appt

R/arima.R, tests/testthat/test-arima.R
This makes the output of `arimaorder()` more human readable, and now users can select the model order using name-based instead of only position-based indexing.
```
> mod <- auto.arima(wineind)
> arimaorder(mod)
p         d         q         P         D         Q Frequency 
1         1         2         0         1         1        12 
> arimaorder(mod)["P"]
P 
0 
> arimaorder(mod)[4]
P 
0 
```
=> Pretty print arimaorder()

R/nnetar.R, tests/testthat/test-nnetar.R
The checks and modification of some parameters like `p` and `lambda` for short or constant data was sometimes being applied when old models were used rather than just new fits. This could lead to unexpected results. I made some changes so those checks were only done if the `model` argument wasn't being used, plus a couple additional tweaks. 
- Adding [`drop = FALSE`](https://github.com/robjhyndman/forecast/compare/robjhyndman:9ea51c8...gabrielcaceres:26eee20#diff-2598d576ddd8340cb32138c059517b22R277) allows the model to be fit with a single observation after accounting for the lags (by keeping `lags.X` as a matrix instead of coercing it into a vector which gave an error). I assume the prior error was the reason [for checking for `n-1`](https://github.com/robjhyndman/forecast/blob/9ea51c889 …
=> Short and constant data in nnetar

R/simulate.R
I noticed that `innov` in `simulate.nnetar` was always scaled. I added a check to make sure the inputs were actually scaled in the original model, otherwise `object$scalex$scale` would be `NULL`. I also modified slightly the code checking for `innov = 0` to make it both clearer and also to avoid unintended problems (say if `innov` equals some other scalar value).
=> simulate.nnetar check before scaling innovations

R/nnetar.R
Noticed a small typo in `forecast.nnetar` doc
=> Fix small typo in documentation

R/lm.R
Resolves #689
The NA in the intervals are from predict.lm, because it computes RSS on residuals that contain NA values.
=> Helped forecast.lm find the user data

R/modelAR.R, R/nnetar.R, R/simulate.R, tests/testthat/test-modelAR.R
This adds functionality to forecast with a user-defined function in a manner similar to `nnetar`, as referenced in #668. I took advantage of the existing `nnetar` code, with some tweaking to use (in principle) any function. It does require a bit more effort from the user in terms of defining the function correctly. The PR includes `modelAR` (what I named the function, although happy hear suggestions), `forecast.modelAR`, `simulate.modelAR`, and unit tests for them. Most unit tests are almost identical to the ones for `nnetar`, plus some additional ones tho compare that output from both functions is identical (given an appropriately defined `FUN` argument for `modelAR`). Although not included here, `CVar` should be straightforward to extend to work with `modelAR`.
Some things are still a …
=> Generalizing nnetar to user-defined functions

R/tscv.R
it often makes sense to not start the cross-validation from beginning but have an initial period that is only used for training.
=> add 'initial' argument for tsCV

R/naive.R
Hello,
I noticed `naive`, `rwf` and `snaive` fail with `lambda = "auto"`. It seems to come from the following commit <https://github.com/robjhyndman/forecast/commit/36c9eeb6625b47c6b4586328d17a81d769237af8>. 
For example:
``` r
library(forecast)
naive(airmiles, lambda = "auto")
#> Error in x * lambda: non-numeric argument to binary operator
rwf(airmiles, lambda = "auto")
#> Error in x * lambda: non-numeric argument to binary operator
snaive(airmiles, lambda = "auto")
#> Error in x * lambda: non-numeric argument to binary operator
```
<sup>Created on 2019-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
This pull request fixes the issue.
=> Fixed naive, rwf, snaive lambda argument

R/HoltWintersNew.R, R/arima.R, R/armaroots.R, R/bats.R, R/calendar.R, R/errors.R, R/etsforecast.R, R/forecastTBATS.R, R/ggplot.R, R/simulate.R, R/theta.R, tests/testthat/test-clean.R, tests/testthat/test-forecast2.R, tests/testthat/test-ggplot.R, tests/testthat/test-graph.R, tests/testthat/test-modelAR.R, tests/testthat/test-newarima2.R, tests/testthat/test-refit.R, tests/testthat/test-season.R, tests/testthat/test-subset.R, tests/testthat/test-thetaf.R
Addresses #841 
There's still partial match warnings that pop up but that's from dependency packages.
I went through the tests to identify partial match issues, so if there's some functions that aren't covered, I most likely missed them.
Also, there's one test case `expect_silent` that I had to remove since `bizdays` gives plenty of partial match warnings. 
Please let me know if you want me to squash commits.
=> Rectify partial match warnings

R/mstl.R, R/newarima2.R
These are the solutions I came up with to problems that crop up when making use of the new capabilities provided by 70cc736295521422c7bd4be7536c61691a380770 , which made in the context of #838 . Whether you are interested in these patches or not, I thought you might want to be notified about these issues.
=> Support for using stlm when missing values occur at the beginning of the response variable

R/arima.R
When setting parameter Parallel=T, the system was giving error
`Error in checkForRemoteErrors(val) :
4 nodes produced errors; first error: object 'max.order' not found`
function "par.all.arima" used max.order which is not passed in the function.
The issue has been mitigated by exporting max.order in the cluster
=> Exported max.order in the cluster for parallel processing.

R/errors.R, tests/testthat/test-arfima.R, tests/testthat/test-arima.R
Current behavior:
```
> library(forecast)
> mod <- arfima(wineind)
> accuracy(mod)
Error in accuracy.default(mod) : 
First argument should be a forecast object or a time series.
```
New behavior:
```
> mod <- arfima(wineind)
> accuracy(mod)
ME     RMSE      MAE       MPE     MAPE     MASE       ACF1
Training set 107.9382 5065.181 3926.056 -3.751643 16.22077 1.995578 0.01095209
```
=> Accuracy for ARFIMA

R/arima.R
fixes issue #855 and fixes pull request #830
The cluster of nodes is created in the non-exported function `search.arima()`. The nodes are unable to access the variables that are passed to this function because the cluster is defined/created _inside_ the `search.arima()` function. 
The nodes cannot access the variables because the variables that are able to be accessed come from the default for the function `clusterExport()` which is `clusterExport(cl = NULL, varlist, envir = .GlobalEnv)`. The variables passed into `search.arima()` do not exists at the `.GlobalEnv` level, they exist within the local function. Thus, we set `envir=environment()` to capture this  function's variables which allows `par.all.arima()` to access them when on other nodes:  `all.models <- parLapply(cl = cl, X = …
=> Parallel computing when using `auto.arima()`

R/ggplot.R
"labels" was left unused in ggsubseriesplot().
This commit makes the function check if labels is supplied and give priority to the user-supplied labels.
=> Make use of the "labels" parameter in ggsubseriesplot

R/newarima2.R
I noticed that `auto.arima` does not print the complete model information when `xreg` and `trace=TRUE` are used. I think it should print `Regression with {arima model} errors` at each step.
The problem arises due to the following lines,
https://github.com/robjhyndman/forecast/blob/e9c4d22f57835748c53453edbca564ca5d15089a/R/newarima2.R#L786-L790
Since `xreg` is added to `fit` after `cat`, `arima.string` ignores it, according to the following lines,
https://github.com/robjhyndman/forecast/blob/e9c4d22f57835748c53453edbca564ca5d15089a/R/newarima2.R#L849-L855
This PR solves the problem.
=> Print right ARIMA model when trace=TRUE

DESCRIPTION, R/forecast-package.R, man/forecast-package.Rd
Fix `"_PACKAGE"` documentation alias conflict check errors.
https://roxygen2.r-lib.org/articles/rd.html#packages
> By default, aliases will be added so that both `?pkgname` and `package?pkgname` will find the package help. If there’s an existing function called pkgname, use `@aliases {pkgname}-package` to override the default.
=> Update package docs to avoid conflict with generics::forecast reexport

tests/testthat/test-calendar.R
This updates the `bizdays()` tests to work with the updated information in 'timeDate'. I have made them conditional on 
'timeDate (>= 4021.105)', since the values returned by older versions were incorrect in some cases.
I would appreciate if you could update 'forecast' on CRAN since I need to submit a revision to deal with a new error in timeDate due to a recent change  in R-devel of as.character() for `POSIX*t` objects.
Long story: 
I have completed the update for the New York stock exchange's non-business days. I used information from NSE itself, so they should be complete. Further changes to historical holidays will be needed only if there are bugs. Similarly for Toronto, but not so exhaustively. Also, although the holiday functions in 'timeDate' technically may be correct to return …
=> update bizdays tests for timeDate (>= 4021.105)

R/forecast.R
```r
library(forecast)
mod <- Arima(log(AirPassengers), c(0,1,1), include.drift = TRUE)
mod
head(fitted(mod, h = 1)) # ok
head(fitted(mod, h = 2)) # Only NA
```
I solved the problem by fixing the forecast function [`hfitted()`](https://github.com/robjhyndman/forecast/blob/5cb1510af7a165c9511764dfbf16d199029f609a/R/forecast.R)
```r
head(fitted(mod, h = 2))
```
In function [`hfitted()`](https://github.com/robjhyndman/forecast/blob/5cb1510af7a165c9511764dfbf16d199029f609a/R/forecast.R) line 486-489
```r
if (!is.null(object$xreg)) {
refitarg$xreg <- ts(object$xreg[1:i, ], start = tspx[1], frequency = tspx[3])
fcarg$xreg <- ts(object$xreg[(i + 1):(i + h), ], start = tspx[1] + i / tspx[3], frequency = tspx[3])
}
```
The object `refitarg$xreg` has two drifts instead of just one, and so the …
=> hfitted bug

R/nnetar.R, tests/testthat/test-nnetar.R
Closes issue [#935](https://github.com/robjhyndman/forecast/issues/935).  
- Changes the creation of the vector `lags` in the case when `p = 0` and `P > 0` to the correct collection of lags by checking for that combination of inputs and using `seq_len()` rather than `1:p` for safety.
- Adds a check in `nnetar()` that will `stop()` with an error if both `p = 0` and `P = 0`, so at least one type of lag must be requested.
- In the case of non-seasonal data (`m = 1`) if the user sets `p = 0`, it will fall back to the default calculation for `p` with a warning.
- Modifies description of the argument `p` to document what happens if `p = 0`
- Added tests for the seasonal only lag case mimicking the existing tests for default size
- Added test for stopping in the case that the user sets both `p = …
=> Allow nnetar models with only seasonal lags

R/arima.R, R/forecast.R
Hi @robjhyndman. Working with the forecast function `hfitted` I found a solution to make it faster in the ARIMA case by also looking at Fable's implementation. So, the `hfitted` function is splitted into two: `hfitted.default` and `hfitted.Arima`. The first is the general implementation, and the second is a re-implementation of the Fable's [`hfitted.ARIMA`](https://github.com/tidyverts/fable/blob/b33661279bd65b050f0125386ed8b27e0c3286b1/R/arima.R#L651) function with the `KalmanRun` and `KalmanForecast` functions.
If you're interested, here I did a comparison in terms of computational time (the fitted returns are equal):
```r
library(forecast)
library(microbenchmark)
mod <- auto.arima(AirPassengers)
benchtime <- microbenchmark("old_version" = forecast:::hfitted(mod, h = 2), 
"new_version" …
```
=> Multi-step fitted ARIMA faster solution

R/arfima.R, R/checkresiduals.R, R/ets.R, R/forecast.R, R/getResponse.R, R/ggplot.R, R/lm.R, R/newarima2.R, R/tbats.R, R/tscv.R
- replace `is.element("try-error", class(x))` with `inherits(x, "try-error")`
- replace `is.element("ts", class(x))` with `is.ts(x)`
- replace `is.element("numeric", class(x))` with `is.numeric(x)`
=> refactor: use more `inherits()` for error checking

DESCRIPTION, R/ggplot.R
size arg is deprecated moving to linewidth for reference: https://www.tidyverse.org/blog/2022/11/ggplot2-3-4-0/#hello-linewidth
Fixes the current deprecation warnings in the tests.
=> fix: replace deprecated size with linewidth in `ggplot2::geom_rect()`

R/HoltWintersNew.R, R/arima.R, R/bats.R, R/checkresiduals.R, R/fitBATS.R, R/fitTBATS.R, R/simulate.R, R/tbats.R
Some of the exported functions with boolean args, might also benefit from the `isTRUE(x)`/`isFALSE(x)` pattern to make them more robust.
=> refactor: remove redundant equals test in logical expressions

R/arima.R, R/ggplot.R, R/guerrero.R, R/newarima2.R
Checking names in data.frame call is rather expensive:
``` r
x <- rnorm(1e5)
bench::mark(
data.frame(x = x),
data.frame(x = x, check.names = FALSE)
)
#> # A tibble: 2 × 6
#>   expression                             min median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>                          <bch:> <bch:>     <dbl> <bch:byt>    <dbl>
#> 1 data.frame(x = x)                   30.1µs 33.4µs    28719.        0B     37.4
#> 2 data.frame(x = x, check.names = FA… 21.8µs 23.5µs    40706.        0B     40.7
```
<sup>Created on 2025-09-18 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
=> perf: disable checking names in data.frame call
