README.md
I think these would be helpful. Many other open-source R packages show those stats on Github. Let me know what you think.
=> added more useful badges on README

R/lm.R, inst/tests/test-tslm.R
Hi Rob, I helped you adding the check for this issue #112 
The bug is now fixed.
=> fixed issue112 bug. Checks whether the data is univariate time series

README.md
The coverage status badge is broken. In stead of showing a percentage of coverage, it shows "inaccessible".
=> fixed broken coverage status

R/errors.R, R/getResponse.R
Merge correct branch with ```accuracy()``` support for bats and tbats objects
=> Accuracy for tbats/bats objects

R/newarima2.R
Verification of output and benchmarks
```
is.constant <- function(x)
{
x <- as.numeric(x)
y <- rep(x[1],length(x))
isequal <- all.equal(c(x),y)
return(isequal==TRUE)
}
is.constant2 <- function(x)
{
x <- as.numeric(x)
y <- rep(x[1], length(x))
return(identical(x, y))
}
require(microbenchmark)
testseries <- rep(1, 10^5)
is.constant(testseries) == is.constant2(testseries)
microbenchmark(is.constant(testseries), is.constant2(testseries))
testseries <- c(rep(1, 10^5), 100)
is.constant(testseries) == is.constant2(testseries)
microbenchmark(is.constant(testseries), is.constant2(testseries))
testseries <- c(100, rep(1, 10^5), 100)
is.constant(testseries) == is.constant2(testseries)
microbenchmark(is.constant(testseries), is.constant2(testseries))
testseries <- c(rep(1, 10^5), 100) …
```
=> Speed up is.constant() by an order of magnitude

inst/tests/test-arima.R
test arimaorder, forecast.Arima, search.arima, and forecast.ar
=> Additional unit tests for arima.R

R/arima.R, R/forecast.R
If some upper prediction interval is Inf, set plot.conf = FALSE
resolve #160
=> Close issue 160

inst/tests/test-arima.R, inst/tests/test-forecast2.R
Tests for forecast.ar(), as.character.Arima(), forecast.StructTS(), and refitting Arima models.
=> Add more unit tests

R/HoltWintersNew.R, man/ses.Rd
Fixes #165  Fixes for `seasonal` and `initial` arguments in `holt()` and `hw()`
=> Close issue 165

R/HoltWintersNew.R, inst/tests/test-dshw.R
Add unit tests for tbats objects and dshw forecasts
=> Create unit tests for tbats and dshw

R/graph.R, inst/tests/test-armaroots.R, inst/tests/test-nnetar.R, inst/tests/test-spline.R, man/ts.display.Rd
Fixes #177 
Adds unit tests for armaroots, nnetar, and splinef
=> Fixes #177

R/arima.R
I am also experiencing issues with #111. I believe this code change fixes the issue.
=> Support drift models with xreg

man/ma.Rd
Clarification on details and usages
=> ma manfile additions

R/forecast.R
=> Issue #200: Unnecessary plot.forecast() warning

R/DM2.R, R/acf.R, R/arima.R, R/bats.R, R/ets.R, R/forecast.R, R/nnetar.R, R/season.R, R/spline.R
Enhances readability for ggplot autoplot implementation
=> Added is.class(object) functions

R/forecast.varest.R, R/mforecast.R, tests/testthat/test-mforecast.R
Also reorganised files for mforecast functions
=> Added support for forecasting mlm objects

R/season.R, man/seasonal.dummy.Rd, tests/testthat/test-season.R
Also made tab spacing for these functions more consistent with the
forecast package.
=> Merged fourier/fourierf and seasonaldummy/seasonaldummyf

R/graph.R
Not sure why travis can't find qpdf
=> Small rounding fix for #199

R/forecast.varest.R, R/mforecast.R
Also fixed plotting for non mlm modelled forecast objects.
=> Changed res->residuals for mforecast objects

R/lm.R, R/wrangle.R
For use with ggplot ggproto objects
=> Condensed time()->TSP into a helper function

NAMESPACE, R/ggplot.R, R/graph.R, man/autoplot.acf.Rd, man/autoplot.decomposed.ts.Rd, man/autoplot.stl.Rd, man/autoplot.ts.Rd, man/forecastplot.Rd, man/fortify.forecast.Rd, man/geom_forecast.Rd, man/is.constant.Rd, man/is.forecast.Rd, man/is.model.Rd, man/plot.Arima.Rd, man/plot.ets.Rd, man/plot.mforecast.Rd, man/seasonplot.Rd, man/stat_forecast.Rd
=> ggplot2 support for forecast package

NAMESPACE, R/ggplot.R, man/autoplot.stl.Rd, man/forecastplot.Rd, man/geom_forecast.Rd, man/is.constant.Rd, man/is.model.Rd, man/plot.mforecast.Rd, man/stat_forecast.Rd
Fix for "Error: could not find function "autoplot""
=> Fix for autoplot namespace

R/ggplot.R, man/autoplot.acf.Rd, man/autoplot.decomposed.ts.Rd, man/autoplot.stl.Rd, man/autoplot.ts.Rd, man/plot.Arima.Rd, man/plot.ets.Rd, man/plot.mforecast.Rd, man/seasonplot.Rd
Also added library(ggplot2) to the man files.
=> Improved ggplot2 function/object definitions

NAMESPACE, R/ggplot.R, man/autoplot.acf.Rd, man/autoplot.decomposed.ts.Rd, man/autoplot.stl.Rd, man/autoplot.ts.Rd, man/forecastplot.Rd, man/plot.Arima.Rd, man/plot.ets.Rd, man/plot.mforecast.Rd, man/seasonplot.Rd
I'll continue committing to this pull until I fix travis errors.
=> S3 method consistency (autoplot)

R/ggplot.R
Fixed missing call to seasonplot via ggplot=FALSE
=> Fix to ggseasonplot

NAMESPACE, R/ggplot.R, man/ggmonthplot.Rd
Creates a ggplot version of monthplot()
Note: Should the mean line still be red? Black for consistency with monthplot() ?
=> Added ggmonthplot()

NAMESPACE, R/ggplot.R, man/forecastplot.Rd, man/ggmonthplot.Rd
Also fixes up documentation mismatches
=> Added support for autoplot.ar()

NAMESPACE, R/ggplot.R, man/autoplot.acf.Rd
Also updated consistency of autoplot.acf arguments
=> Added autoplot.mpacf, ggAcf, ggPacf, ggCcf, ggtaperedacf, ggtaperedpacf

NAMESPACE, R/ggplot.R, man/ts.display.Rd
Also made lag 0 removal more consistent for ggPacf
=> Fixed support for Ccf via autoplot.acf

R/acf.R, R/ggplot.R, man/autoplot.acf.Rd, man/autoplot.decomposed.ts.Rd, man/autoplot.stl.Rd, man/autoplot.ts.Rd, man/forecastplot.Rd, man/ggmonthplot.Rd, man/plot.Arima.Rd, man/plot.ets.Rd, man/plot.mforecast.Rd, man/seasonplot.Rd
Also removed main, ylab, xlab arguments (still functioning in dots via ggAddExtras helper function).
=> ggAcf and ggtsdisplay improvements

R/ggplot.R, tests/testthat/test-newarima2.R
=> Fixed taperedacf without CI.

R/ggplot.R
=> Fixed seriesname parsing

R/lm.R, tests/testthat/test-tslm.R
Also made forecast.lm() work harder to find newdata variables if they're functions.
=> Fixed tslm timeseries variable subsetting

R/ggplot.R, man/autoplot.ts.Rd
#285 
Note: This does not impact geom_forecast() functionality.
=> Added faceting for autoplot.mts

R/HoltWintersNew.R, man/ses.Rd
=> Added BoxCox transformation support for ses, holt, hw.

R/ggplot.R
#296
(splitting ellipsis arguments are weird).
=> Fixed internal labelling for ggtsdisplay

R/ggplot.R, man/ts.display.Rd
=> Added theme support to ggtsdisplay

R/ggplot.R
autoplot(USAccDeaths, xlim=c(1975,1978), ylim=c(0,12000))
=> Added support for xlim and ylim in autoplot()

R/newarima2.R
=> Remove residual bugs from optim.method to ... transition

NAMESPACE, R/ggplot.R, man/gglagplot.Rd
=> Added gglagplot() and gglagchull()

R/ggplot.R
=> Resolved gglagplot slowness and 'ugly points'

R/ggplot.R, man/gglagplot.Rd
=> Added points to gglagplot() when do.lines=FALSE

R/forecast.R
=> Added xreg support for h-step fits

R/ggplot.R
=> Backtransform BoxCox for model data extraction (tslm)

R/lm.R
Should fix functions that use trend or season, such as tslm(y~poly(trend, 3))
=> Made tslm() always add trend+season to data when not provided

R/ggplot.R
=> Retained column ordering in autoplot.mts

R/lm.R, tests/testthat/test-tslm.R
=> Made tslm() return same object structure as lm()

NAMESPACE, man/plot.Arima.Rd
=> Exported autoplot.* methods to namespace

R/ggplot.R
Also slight related fix in autoplot.stl for custom labels.
#398
=> Added autoplot.seas()

R/ggplot.R, man/autoplot.decomposed.ts.Rd
Resolves #397
```R
library(fpp)
autoplot(decompose(elecequip))
```
=> Made autoplot.decomposed.ts() consistent with autoplot.stl()

R/ggplot.R
=> Removed missing value warning from autoplot.[m]ts()

R/ggplot.R
=> Fixed off-by-one error in gglagplot colours

R/HoltWintersNew.R, R/arfima.R, R/arima.R, R/dshw.r, R/ets.R, R/etsforecast.R, R/fitBATS.R, R/fitTBATS.R, R/forecast2.R, R/forecastBATS.R, R/forecastTBATS.R, R/lm.R, R/mforecast.R, R/naive.R, R/season.R, R/spline.R, man/arima.Rd, man/dshw.Rd, man/fitted.Arima.Rd, man/forecast.Arima.Rd, man/forecast.HoltWinters.Rd, man/forecast.StructTS.Rd, man/forecast.bats.Rd, man/forecast.ets.Rd, man/forecast.lm.Rd, man/forecast.mlm.Rd, man/forecast.stl.Rd, tests/testthat/test-biasadj.R
Enhancement #326
Achieved by having lambda contain the attribute biasadj
=> biasadj now defaults to the value given in the modelling stage

R/season.R, man/forecast.stl.Rd
=> Support for re-fitting in stlm

R/arfima.R, man/arfima.Rd, tests/testthat/test-refit.R
=> Added re-fit support for arfima

R/arima.R, man/forecast.Arima.Rd
As ar() does not support biasadj
=> Changed default for biasadj in forecast.ar

R/forecast.R
Allows usage like:
```R
fit <- forecast(mdeaths)
refit <- forecast(fdeaths, model=refit)
```
=> Added support for forecast objects to be re-fit in forecast.ts

R/ggplot.R
Grab the actual data, not the fitted data!
=> Bugfix for autoplot.seas

R/ggplot.R
- Start of a generic timeseries break function for scale_x_continuous()
- geom_forecast() confidence intervals have been fixed.
=> ggplot improvements

R/ggplot.R
Seasonality to be added, as specified in #429 
X-axis is now pretty, and extends to incorporate changes in the plot limits
=> Quickfix for ugly autoplot.ts breaks

R/ggplot.R
Wish I knew about optional_aes earlier!
Couldn't find it documented anywhere.
=> Fixed issues with geom_forecast(plot.conf=FALSE)

R/ggplot.R, man/autoplot.ts.Rd
=> Added series argument to autoplot.ts() and ggts()

R/ggplot.R
Rather than previous functionality of connecting same years at Jan/Dec
Resolves issue #437
=> Changed ggseasonplot(polar=TRUE) to connect successive years

NAMESPACE, R/ggplot.R, man/autolayer.Rd, man/autoplot.ts.Rd
=> Added autolayer S3 generic with ts and mts methods

R/ggplot.R
=> Added geom_forecast support for sending alpha channels via colour

R/baggedETS.R
=> Added method attribute to baggedETS forecast object

R/forecast.R, R/ggplot.R, man/forecastplot.Rd, man/fortify.forecast.Rd, man/geom_forecast.Rd
Specifically works for:
- plot.forecast
- autolayer.forecast
- geom_forecast
- fortify.forecast
=> Added showgap option to forecast plots

NAMESPACE, R/ggplot.R, man/autoplot.seas.Rd, tests/testthat/test-ggplot.R
=> Added autoplot.StructTS

R/ggplot.R
This should fix the "yellow forecast line problem"
=> Fixed series argument in autolayer.forecast

R/errors.R, R/forecast.varest.R, R/getResponse.R, R/ggplot.R, R/mforecast.R, man/plot.mforecast.Rd, tests/testthat/test-mforecast.R
=> New, consistent mforecast class structure

R/ggplot.R
Also simplified labeller function for gglagplot. Much nicer now! Fixes issue #493.
=> Fixed gglagplot facet ordering for lags > 40

R/lm.R
=> Added more informative warnings in forecast.lm

R/forecastBATS.R, R/forecastTBATS.R
=> Added level information to interval column names

R/getResponse.R, R/mforecast.R
Quick note - didn't have time to test it, so let travis run to completion. There is a slim chance that this breaks things elsewhere.
Fix #502
=> Fixed bug with autoplot.mforecast

NAMESPACE, R/ggplot.R, man/autoplot.ts.Rd
=> Added autoplot.msts and autolayer.msts

R/ggplot.R
=> Added autoplot.mts check for multiple columns

R/ggplot.R
=> Added univariate msts ggplot support

R/ggplot.R, man/autoplot.ts.Rd
=> Made ggplot msts functions more consistent and clear

R/ggplot.R
Plotting more than one newdata point resolved.
Fix issue #523
=> Resolved issue with autoplot.forecast (lm)

NAMESPACE, R/subset.R, man/subsetts.Rd
=> Added subset.msts

R/lm.R
=> Fixed forecast.lm bug with lm model

R/msts.R
=> Fixed msts disregarding dot inputs

R/ggplot.R, man/geom_forecast.Rd, man/seasonplot.Rd
=> Added season.labels to ggseasonplot

R/arima.R
=> Fixed constant series Arima models lacking tsp

R/tscv.R, man/tsCV.Rd
=> Added rolling window option for tsCV

R/forecast2.R
Resolves #612
(maybe the average sd is not the best measure, or is inapplicable for describing model components when using bootstrap intervals, I leave this to @robjhyndman to comment)
=> Added more bootstrap model information to meanf

R/tscv.R
I know it's super minor, but I fixed a typo in the comments for CVar.
=> Fixed typo in CVar comment

R/baggedETS.R, R/tscv.R
Addresses issue #600 and seems to also resolve issue #531, though I'm not sure why. We now have a parameter to pass in the base forecast function. 
Not so sure if BaggedETS is still an adequate name for the function, as it now can also build a bagged auto.arima and others. Let me know your thoughts, Rob.
The second commit adds calculation of the Ljung-Box test on the residuals of cross-validation, as proposed in the latest version of the CV paper.
=> baggedETS now accepts a parameter for the base forecasting function

R/ggplot.R
=> Fixed GeomForecast mishandling forecasted NA values

R/ggplot.R
(quick fix as the implementation will be overhauled with tsibble)
Resolves #624
=> Fixed PI=FALSE causing issues for GeomForecast

R/ggplot.R
Should resolve plotting issues with non-integer seasonality and short series.
```R
ggsubseriesplot(fpp2::gasoline)
```
=> Added check for length of seasonal subseries

DESCRIPTION
Many people in China have the same name as mine so this PR would help provide a unique identifier.
=> Add my ORCID and email

R/nnetar.R
Updated `forecast.nnetar` examples as per #692
=> Update forecast.nnetar examples

R/ets.R, man/ets.Rd
=> Added na.action to ets

R/newarima2.R, man/auto.arima.Rd
=> Added nmodels option for auto.arima

R/acf.R, R/ggplot.R
Resolves #760
``` r
library(forecast)
Acf(fpp2::uschange)
```
``` r
ggAcf(fpp2::uschange)
```
``` r
Pacf(fpp2::uschange)
```
``` r
ggPacf(fpp2::uschange)
```
<sup>Created on 2018-11-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
=> Added multivariate support for ggAcf, ggPacf, etc.

R/arima.R, R/nnetar.R, tests/testthat/test-arima.R, tests/testthat/test-modelAR.R, tests/testthat/test-nnetar.R
=> Added forecast.Arima checks for xreg colum names

R/lm.R
Proposed fix for https://github.com/robjhyndman/forecast/issues/803
=> Backtransform response variable for tslm

R/clean.R
=> Allow to pass iterate option for tsclean 

R/DM2.R
- Introduced a second long-run-variance estimator  with bartlett-kernel.
- Introduced a new Input-Parameter (varestimator) to decide the lrv-estimator to be used.
- Enhanced the documentation regarding the new implementation.
=> #898  Update to DM2.R

DESCRIPTION, tests/testthat/test-accuracy.R, tests/testthat/test-acf.R, tests/testthat/test-arima.R, tests/testthat/test-armaroots.R, tests/testthat/test-bats.R, tests/testthat/test-boxcox.R, tests/testthat/test-calendar.R, tests/testthat/test-dshw.R, tests/testthat/test-ets.R, tests/testthat/test-forecast.R, tests/testthat/test-forecast2.R, tests/testthat/test-ggplot.R, tests/testthat/test-graph.R, tests/testthat/test-hfitted.R, tests/testthat/test-mforecast.R, tests/testthat/test-modelAR.R, tests/testthat/test-msts.R, tests/testthat/test-nnetar.R, tests/testthat/test-refit.R, tests/testthat/test-spline.R, tests/testthat/test-subset.R, tests/testthat/test-tbats.R, tests/testthat/test-tslm.R, tests/testthat/test-wrangle.R
See motivation in https://github.com/hadley/reshape/pull/94
=> Migrate to testthat 3e

src/updateTBATSMatrices.cpp
Flagged by `-Wunused-variable`
=> Remove unused variable

DESCRIPTION, NEWS.md, R/attach.R
=> Add withr preserve seed for .onAttach random tip

DESCRIPTION
=> Add 'scales' to Suggests

R/bats.R, R/checkresiduals.R, R/clean.R, R/components.R, R/ets.R, R/forecast2.R, R/forecastBATS.R, R/forecastTBATS.R, R/ggplot.R, R/guerrero.R, R/lm.R, R/mstl.R, R/msts.R, R/season.R, R/subset.R, R/tbats.R, R/unitRoot.R
- replace `"class" %in% class(object)` with preferred `inherits(object, "class")`
- replace `"ts" %in% class(object)` or equivalent nto direct `is.ts(object)` check
- replace `"mts" %in% class(object)` or equivalent to direct `is.mts(object)` check
=> refactor: check for class membership with `inherits()`

R/acf.R, R/arima.R, R/armaroots.R, R/checkresiduals.R, R/errors.R, R/ggplot.R, R/lm.R, R/mstl.R, R/tbats.R
Last batch of `is.element()` to `inherits()` or direct class check replacements.
=> refactor: replace more `is.element()` with `inherits()` or equivalent

R/ggplot.R
Removes the else block after `if (requireNamespace(...) stop()` since calling`stop()`, reducing the nesting of the code and making it easier to read.
To see the minor change, hide the whitespace changes in the diff viewer.
=> refactor(ggplot): remove some of the nesting for package check

.Rbuildignore
To signal the usage of air. I assume the default configs were used.
=> chore: add air config

R/DM2.R, R/HoltWintersNew.R, R/acf.R, R/arfima.R, R/arima.R, R/baggedModel.R, R/bats.R, R/dshw.r, R/ets.R, R/forecast.R, R/forecast2.R, R/ggplot.R, R/graph.R, R/mean.R, R/modelAR.R, R/mstl.R, R/naive.R, R/newarima2.R, R/nnetar.R, R/spline.R, R/tbats.R, R/tscv.R, R/unitRoot.R, man/autoplot.ts.Rd
Use `deparse1()` to ensure character length of one.
=> refactor: replace `deparse(substitute())` with `deparse1(substitute())`
